version: "3.3"
services:
  server:
    container_name: server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  proxy:
    container_name: nginx_proxy
    restart: unless-stopped
    depends_on: 
      - server
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
